name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
    - name: Set environment variable
      run: echo "PORT=8080" >> $GITHUB_ENV

    - name: Verify environment variable
      run: echo $PORT

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker buildx build --platform linux/amd64 -t tutko/intents-api:1.0 .

    - name: Push Docker image
      run: docker push tutko/intents-api:1.0

    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@v1.1.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
        working-directory: /home/ec2-user
        command: |
          sudo docker stop $(sudo docker ps -q --filter ancestor=tutko/intents-api:1.0)
          sudo docker run -d -p 80:8080 -e PORT=8080 tutko/intents-api:1.0
        comment: Docker deployment of tutko/intents-api
