name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PORT: 8080

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker buildx build --platform linux/amd64 -t tutko/intents-api:1.0 .

    - name: Push Docker image
      run: docker push tutko/intents-api:1.0

    - name: Decode and write SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > /tmp/ssh_key
        chmod 600 /tmp/ssh_key

    - name: SSH to EC2 and deploy
      env:
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        USER_NAME: ${{ secrets.EC2_USER }}
        HOSTNAME: ${{ secrets.EC2_HOST }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
          sudo docker stop $(sudo docker ps -q --filter ancestor=tutko/intents-api:1.0)
          sudo docker run -d -p 80:8080 -e PORT=8080 tutko/intents-api:1.0
        EOF
